### ISSUE TITLE
Permit integers as keys

### ISSUE THREAD

**Issue by benlinton** [ahorner/text-helpers#8]
Given:
```
en:
  steps:
    1: "First step"
    2: "Second step"
```
I'm able to use rails built in translations `=t ("steps.1")`.  

But `text_helpers` gem fails `= text("steps.1")` to find the translation; unless I change `1` to `one` (which makes it more difficult to iterate over).

**Comment by soulcutter** [comment]
I poked at this a bit and am not sure how this works in rails, but not in text_helpers. A workaround is to use keys like this:

```yaml
en:
  steps:
    "1": "First step"
    "2": "second step"
```
